### ISSUE TITLE
一些缺少和问题

### ISSUE THREAD

**Issue by yangtzech** [tonngw/LeetCode021#2]
你好，我最近又发现了一些问题：

数组缺少：[76.最小覆盖子串](https://programmercarl.com/0209.%E9%95%BF%E5%BA%A6%E6%9C%80%E5%B0%8F%E7%9A%84%E5%AD%90%E6%95%B0%E7%BB%84.html#%E7%9B%B8%E5%85%B3%E9%A2%98%E7%9B%AE%E6%8E%A8%E8%8D%90)

哈希表缺少题目：[49.字母异位词分组](https://programmercarl.com/0242.%E6%9C%89%E6%95%88%E7%9A%84%E5%AD%97%E6%AF%8D%E5%BC%82%E4%BD%8D%E8%AF%8D.html#%E7%9B%B8%E5%85%B3%E9%A2%98%E7%9B%AE)

贪心算法缺少：[968.监控二叉树](https://programmercarl.com/0968.%E7%9B%91%E6%8E%A7%E4%BA%8C%E5%8F%89%E6%A0%91.html)

[股票系列问题](https://github.com/tonngw/LeetCode021#%E8%82%A1%E7%A5%A8%E7%B3%BB%E5%88%97%E9%97%AE%E9%A2%98)可以把[122.买卖股票的最佳时机II](https://programmercarl.com/0122.%E4%B9%B0%E5%8D%96%E8%82%A1%E7%A5%A8%E7%9A%84%E6%9C%80%E4%BD%B3%E6%97%B6%E6%9C%BAII%EF%BC%88%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%EF%BC%89.html)再放一遍

[09. 最佳买卖股票时机含冷冻期](https://leetcode-cn.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/)「[题解](https://leetcode-cn.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/solution/zhuang-tai-ji-dp-309-zui-jia-mai-mai-gu-dylw4/)」编号应该是309

**Comment by tonngw** [comment]
以上列出的问题已全部补充和更正，感谢小伙伴的指出~

**Comment by yangtzech** [comment]
谢谢

**Comment by yangtzech** [comment]
谢谢
